---
# only publish new version
- name: "Publish new version of Content-View"
  theforeman.foreman.content_view_version:
    username: "{{ foreman_user }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    organization: "{{ organization.key }}"
    content_view: "{{ content_view }}"
